# Generated by Django 6.1 on 2026-08-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
